name: Testing Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run_Selenium_Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    # - uses: browser-actions/setup-chrome@latest
    # - run: chrome --version
     
    - name: Run Selenium tests
      run: |
        cd selenium-test
        mvn clean test   









  Run_Nightwatch_tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest,windows-latest,macos-latest]
        
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Nightwatch Test Started!
        
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: npm-install
        run: |
           cd nightwatch-test
           npm ci
      - name: Run Nightwatch tests
        run:  |
           cd nightwatch-test
           npx nightwatch --headless
      - name: Archive test reports
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: nightwatch-report-${{ matrix.os }}
          path: nightwatch-test/tests_output

# Running Test using xvfb
   # Run_Nightwatch_Tests:
   #  # The type of runner that the job will run on
   #  runs-on: ${{ matrix.os }}
   #  strategy:
   #    matrix:
   #      os: [ubuntu-latest]
        
   #  # Steps represent a sequence of tasks that will be executed as part of the job
   #  steps:
   #  # Runs a single command using the runners shell
   #    - name: Run a one-line script
   #      run: echo Nightwatch Test Started!
        
   #    - name: Checkout code
   #      uses: actions/checkout@v4
        
   #    - name: Checkout Repository
   #      uses: actions/checkout@v4
   #      with:
   #       #node-version: $undefined
   #       cache: 'npm'
 
   #    - name: Use Node.js
   #      uses: actions/setup-node@v4
   #      with:
   #        node-version: 21
   #    - name: npm-install
   #      run: |
   #         cd nightwatch-test
   #         npm ci
   #    - name: xvfb-install   
   #      run:  |
   #         cd nightwatch-test
   #         sudo apt-get install xvfb
   #    - name: Run Nightwatch tests
   #      run:  |
   #         cd nightwatch-test
   #         xvfb-run --auto-servernum npm test -- --env chrome
